version: "3.7"
services:
  mq:
    build:
      context: ./config
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"
    ports:
    - 1414:1414
    - 9443:9443

  topic-producer:
    image: pub-sub-topic-showcase/topic-producer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_TOPIC: DEV.TOPIC.DEMO
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9080:9080
    depends_on:
    - mq

  topic-consumer-a:
    image: pub-sub-topic-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_TOPIC: DEV.TOPIC.DEMO
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9081:9080
    depends_on:
    - mq

  topic-consumer-b:
    image: pub-sub-topic-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_TOPIC: DEV.TOPIC.DEMO
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9082:9080
    depends_on:
    - mq

  topic-consumer-c:
    image: pub-sub-topic-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_TOPIC: DEV.TOPIC.DEMO
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9083:9080
    depends_on:
    - mq

  topic-consumer-d:
    image: pub-sub-topic-showcase/topic-consumer-durable:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_TOPIC: DEV.TOPIC.DEMO
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9084:9080
    depends_on:
    - mq

  topic-consumer-dlq:
    image: pub-sub-topic-showcase/topic-consumer-dlq:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_QUEUE: QUEUE.DEAD.LETTER
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9085:9080
    depends_on:
    - mq

  #topic-consumer-shared-a:
  #  build:
  #    context: topic-consumer-shared
  #  environment:
  #    MQ_CHANNEL: DEV.ADMIN.SVRCONN
  #    MQ_QMANAGER: QM1
  #    MQ_TOPIC: DEV.TOPIC.DEMO
  #    MQ_PORT: 1414
  #    MQ_HOST: mq
  #    MQ_USER: admin
  #    MQ_PASSWORD: passw0rd
  #    MQ_SUB_NAME: shared-sub
  #  ports:
  #    - 8081:8080
  #
  #topic-consumer-shared-b:
  #  build:
  #    context: topic-consumer-shared
  #  environment:
  #    MQ_CHANNEL: DEV.ADMIN.SVRCONN
  #    MQ_QMANAGER: QM1
  #    MQ_TOPIC: DEV.TOPIC.DEMO
  #    MQ_PORT: 1414
  #    MQ_HOST: mq
  #    MQ_USER: admin
  #    MQ_PASSWORD: passw0rd
  #    MQ_SUB_NAME: shared-sub
  #  ports:
  #    - 8082:8080
