version: "3.7"
services:
  mq-broker:
    image: mq-showcase/mq-broker:0
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"
    ports:
    - 1414:1414
    - 9443:9443

  jaeger-server:
    image: jaegertracing/all-in-one:1.18.1
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  topic-producer:
    image: mq-showcase/topic-producer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      MQ_CLIENT_ID: topic-producer-1
      MQ_TOPIC: DEV.TOPIC.MESSAGES
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: topic-producer
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9081:9080
    depends_on:
    - mq-broker
    - jaeger-server

  topic-consumer-nondurable:
    image: mq-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_HOST: mq
      MQ_PORT: 1414
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      MQ_TOPIC: DEV.TOPIC.MESSAGES
      MQ_CLIENT_ID: topic-consumer-nondurable
      MQ_SUB_NAME: topic-consumer-nondurable
      MQ_SUB_DURABILITY: NonDurable
      MQ_SUB_SHARED: 'False'
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: topic-consumer-nondurable
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    depends_on:
    - mq-broker
    - jaeger-server

  topic-consumer-durable:
    image: mq-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_HOST: mq
      MQ_PORT: 1414
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      MQ_TOPIC: DEV.TOPIC.MESSAGES
      MQ_CLIENT_ID: topic-consumer-durable
      MQ_SUB_NAME: topic-consumer-durable
      MQ_SUB_DURABILITY: Durable
      MQ_SUB_SHARED: 'False'
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: topic-consumer-durable
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    depends_on:
    - mq-broker
    - jaeger-server

  topic-consumer-shared-a:
    image: mq-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_HOST: mq
      MQ_PORT: 1414
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      MQ_TOPIC: DEV.TOPIC.MESSAGES
      MQ_CLIENT_ID: topic-consumer-shared
      MQ_SUB_NAME: topic-consumer-shared
      MQ_SUB_DURABILITY: Durable
      MQ_SUB_SHARED: 'True'
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: topic-consumer-shared-a
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    depends_on:
    - mq-broker
    - jaeger-server

  topic-consumer-shared-b:
    image: mq-showcase/topic-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_HOST: mq
      MQ_PORT: 1414
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      MQ_TOPIC: DEV.TOPIC.MESSAGES
      MQ_CLIENT_ID: topic-consumer-shared
      MQ_SUB_NAME: topic-consumer-shared
      MQ_SUB_DURABILITY: Durable
      MQ_SUB_SHARED: 'True'
      JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: topic-consumer-shared-b
      JAEGER_REPORTER_LOG_SPANS: "true"
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    depends_on:
    - mq-broker
    - jaeger-server