version: "3.7"
services:
  mq:
    build:
      context: ./config
    environment:
      LICENSE: "accept"
      MQ_QMGR_NAME: "QM1"
    ports:
    - 1414:1414
    - 9443:9443

  queue-producer:
    image: pub-sub-queue-showcase/queue-producer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_QUEUE: DEV.QUEUE.ALIAS
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9080:9080
    depends_on:
    - mq

  queue-consumer-a:
    image: pub-sub-queue-showcase/queue-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_QUEUE: DEV.QUEUE.1
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9081:9080
    depends_on:
    - mq

  queue-consumer-b:
    image: pub-sub-queue-showcase/queue-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_QUEUE: DEV.QUEUE.2
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9082:9080
    depends_on:
    - mq

  queue-consumer-c:
    image: pub-sub-queue-showcase/queue-consumer:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_QUEUE: DEV.QUEUE.3
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9083:9080
    depends_on:
    - mq

  queue-consumer-dlq:
    image: pub-sub-queue-showcase/queue-consumer-dlq:0
    environment:
      MQ_CHANNEL: DEV.ADMIN.SVRCONN
      MQ_QMANAGER: QM1
      MQ_QUEUE: QUEUE.DEAD.LETTER
      MQ_PORT: 1414
      MQ_HOST: mq
      MQ_USER: admin
      MQ_PASSWORD: passw0rd
      WLP_LOGGING_CONSOLE_LOGLEVEL: audit
    ports:
    - 9084:9080
    depends_on:
    - mq
